clockAccessory = true
compassAccessory = true
recoveryCompassAccessory = true
calendarAccessory = true
elytraAccessory = true
spyglassAccessory = true
totemOfUndyingAccessory = true
shulkerBoxAccessory = true
