#Various options that affect individual hats.
[BalanceOptions]

	[BalanceOptions.AquanautHelmet]
		#Whether or not damaging of Aquanaut Helmet should be enabled.
		aquanautHelmetDamageEnabled = true
		#Aquanaut Helmet durability.
		# Default: 600
		# Range: 1 ~ 10000
		aquanautHelmetDurability = 600
		#Aquanaut Helmet effect time of Conduit Power without Efficiency enchantment. (in seconds)
		# Default: 60
		# Range: 10 ~ 120
		aquanautHelmetEffectTimeWithEfficiency0 = 60
		#Aquanaut Helmet effect time of Conduit Power with Efficiency I. (in seconds)
		# Default: 120
		# Range: 10 ~ 180
		aquanautHelmetEffectTimeWithEfficiency1 = 120
		#Aquanaut Helmet effect time of Conduit Power with Efficiency II. (in seconds)
		# Default: 180
		# Range: 10 ~ 240
		aquanautHelmetEffectTimeWithEfficiency2 = 180
		#Aquanaut Helmet effect time of Conduit Power with Efficiency III. (in seconds)
		# Default: 240
		# Range: 10 ~ 300
		aquanautHelmetEffectTimeWithEfficiency3 = 240
		#Aquanaut Helmet effect time of Conduit Power with Efficiency IV. (in seconds)
		# Default: 300
		# Range: 10 ~ 360
		aquanautHelmetEffectTimeWithEfficiency4 = 300
		#Aquanaut Helmet effect time of Conduit Power with Efficiency V. (in seconds)
		# Default: 360
		# Range: 10 ~ 420
		aquanautHelmetEffectTimeWithEfficiency5 = 360

	[BalanceOptions.BunnyEars]
		#Whether or not damaging of Bunny Ears should be enabled.
		bunnyEarsDamageEnabled = true
		#Bunny Ears durability.
		# Default: 450
		# Range: 1 ~ 10000
		bunnyEarsDurability = 450

	[BalanceOptions.ChoppingHat]
		#Whether or not damaging of Chopping Hat should be enabled.
		choppingHatDamageEnabled = true
		#Chopping Hat durability.
		# Default: 300
		# Range: 1 ~ 10000
		choppingHatDurability = 300
		#Chopping Hat speed increase without Efficiency enchantment.
		# Default: 0.2
		# Range: 0.0 ~ 5.0
		choppingHatSpeedWithEfficiency0 = 0.2
		#Chopping Hat speed increase with Efficiency I.
		# Default: 0.4
		# Range: 0.0 ~ 5.0
		choppingHatSpeedWithEfficiency1 = 0.4
		#Chopping Hat speed increase with Efficiency II.
		# Default: 0.6
		# Range: 0.0 ~ 5.0
		choppingHatSpeedWithEfficiency2 = 0.6
		#Chopping Hat speed increase with Efficiency III.
		# Default: 0.8
		# Range: 0.0 ~ 5.0
		choppingHatSpeedWithEfficiency3 = 0.8
		#Chopping Hat speed increase with Efficiency IV.
		# Default: 1.0
		# Range: 0.0 ~ 5.0
		choppingHatSpeedWithEfficiency4 = 1.0
		#Chopping Hat speed increase with Efficiency V.
		# Default: 1.5
		# Range: 0.0 ~ 5.0
		choppingHatSpeedWithEfficiency5 = 1.5

	[BalanceOptions.EnderHelmet]
		#Whether or not damaging of Ender Helmet should be enabled.
		enderHelmetDamageEnabled = true
		#Ender Helmet durability.
		# Default: 80
		# Range: 1 ~ 10000
		enderHelmetDurability = 80
		#Whether or not interdimensional teleporting with the Ender Helmet should be enabled.
		enderHelmetInterdimensionalEnabled = true

	[BalanceOptions.Halo]
		#Whether or not damaging of Halo should be enabled.
		haloDamageEnabled = true
		#Halo durability.
		# Default: 600
		# Range: 1 ~ 10000
		haloDurability = 600

	[BalanceOptions.LuckyHat]
		#Whether or not damaging of Lucky Hat should be enabled.
		luckyHatDamageEnabled = true
		#Lucky Hat durability.
		# Default: 300
		# Range: 1 ~ 10000
		luckyHatDurability = 300
		#Whether or not Unluck effect of Lucky Hat should be enabled after fishing/killing.
		luckyHatUnluckEnabled = true

	[BalanceOptions.MiningHat]
		#Whether or not damaging of Mining Hat should be enabled.
		miningHatDamageEnabled = true
		#Mining Hat durability.
		# Default: 450
		# Range: 1 ~ 10000
		miningHatDurability = 450
		#Whether or not Night Vision effect of Mining Hat should be enabled in dark areas.
		miningHatNightVisionEnabled = true
		#Whether or not wearing a Mining Hat should make Piglins neutral.
		miningHatMakePiglinsNeutralEnabled = true
		#Mining Hat speed increase without Efficiency enchantment.
		# Default: 0.2
		# Range: 0.0 ~ 5.0
		miningHatSpeedWithEfficiency0 = 0.2
		#Mining Hat speed increase with Efficiency I.
		# Default: 0.4
		# Range: 0.0 ~ 5.0
		miningHatSpeedWithEfficiency1 = 0.4
		#Mining Hat speed increase with Efficiency II.
		# Default: 0.6
		# Range: 0.0 ~ 5.0
		miningHatSpeedWithEfficiency2 = 0.6
		#Mining Hat speed increase with Efficiency III.
		# Default: 0.8
		# Range: 0.0 ~ 5.0
		miningHatSpeedWithEfficiency3 = 0.8
		#Mining Hat speed increase with Efficiency IV.
		# Default: 1.0
		# Range: 0.0 ~ 5.0
		miningHatSpeedWithEfficiency4 = 1.0
		#Mining Hat speed increase with Efficiency V.
		# Default: 1.5
		# Range: 0.0 ~ 5.0
		miningHatSpeedWithEfficiency5 = 1.5

	[BalanceOptions.MushroomHat]
		#Whether or not damaging of Mushroom Hat should be enabled.
		mushroomHatDamageEnabled = true
		#Mushroom Hat durability.
		# Default: 80
		# Range: 1 ~ 10000
		mushroomHatDurability = 80
		#Interval the Mushroom Hat is eaten by the player (in ticks). default: 60 (3 seconds)
		# Default: 60
		# Range: 1 ~ 10000
		mushroomHatEatInterval = 60

	[BalanceOptions.PostmanHat]
		#Whether or not damaging of Postman Hat should be enabled.
		postmanHatDamageEnabled = true
		#Postman Hat durability.
		# Default: 600
		# Range: 1 ~ 10000
		postmanHatDurability = 600
		#Whether or not Hunger effect of Postman Hat should be enabled while running.
		postmanHatHungerEnabled = true

	[BalanceOptions.ShulkerHelmet]
		#Whether or not damaging of Shulker Helmet should be enabled.
		shulkerHelmetDamageEnabled = true
		#Shulker Helmet durability.
		# Default: 600
		# Range: 1 ~ 10000
		shulkerHelmetDurability = 600

	[BalanceOptions.StockingCap]
		#Whether or not damaging of Stocking Cap should be enabled.
		stockingCapDamageEnabled = true
		#Stocking Cap durability.
		# Default: 600
		# Range: 1 ~ 10000
		stockingCapDurability = 600

	[BalanceOptions.StrawHat]
		#Whether or not damaging of Straw Hat should be enabled.
		strawHatDamageEnabled = true
		#Straw Hat durability.
		# Default: 600
		# Range: 1 ~ 10000
		strawHatDurability = 600
		#Straw Hat speed increase without Efficiency enchantment.
		# Default: 0.2
		# Range: 0.0 ~ 5.0
		strawHatSpeedWithEfficiency0 = 0.2
		#Straw Hat speed increase with Efficiency I.
		# Default: 0.4
		# Range: 0.0 ~ 5.0
		strawHatSpeedWithEfficiency1 = 0.4
		#Straw Hat speed increase with Efficiency II.
		# Default: 0.6
		# Range: 0.0 ~ 5.0
		strawHatSpeedWithEfficiency2 = 0.6
		#Straw Hat speed increase with Efficiency III.
		# Default: 0.8
		# Range: 0.0 ~ 5.0
		strawHatSpeedWithEfficiency3 = 0.8
		#Straw Hat speed increase with Efficiency IV.
		# Default: 1.0
		# Range: 0.0 ~ 5.0
		strawHatSpeedWithEfficiency4 = 1.0
		#Straw Hat speed increase with Efficiency V.
		# Default: 1.5
		# Range: 0.0 ~ 5.0
		strawHatSpeedWithEfficiency5 = 1.5

	[BalanceOptions.WingHelmet]
		#Whether or not damaging of Wing Helmet should be enabled.
		wingHelmetDamageEnabled = true
		#Wing Helmet durability.
		# Default: 600
		# Range: 1 ~ 10000
		wingHelmetDurability = 600
		#Whether or not Levitation effect of Wing Helmet should be enabled.
		wingHelmetLevitationEnabled = true
