[Dimensions]
	#This is used to calculate the xp you get when you kill a mob in that dimension
	dimensions_drop_rates = ["minecraft:overworld=1", "minecraft:the_nether=1.5", "minecraft:the_end=2"]

["Bosses Drop Rates"]
	#Max drop rate of orbs of leveling from bosses
	max_drop_rate = 3.0
	#Min drop rate of orbs of leveling from bosses
	min_drop_rate = 1.0
	#list of the mobs which will drop the leveling orbs
	bosses_list = ["minecraft:ender_dragon", "minecraft:wither"]
